### ISSUE TITLE
SmartPost Support?

### ISSUE THREAD

**Issue by cjones-swarm** [kylewest/DotNetShipping#37]
How do I go about implementing Fedex SmartPost HubID and Indicia Type w/ the GetRates call and having SmartPost returned as a rate type?

**Comment by kylewest** [comment]
Hi Charles,

I hadn't heard of SmartPost before your post. I managed to find the marketing materials on the FedEx site but none of the developer documentation. Do you have links to those docs?

This isn't something I will be able to tackle in the near future but I'm happy to help you figure it out and submit a pull request. The work most likely involves setting/changing some parameters in the [FedExProvider](https://github.com/kylewest/DotNetShipping/blob/master/DotNetShipping/ShippingProviders/FedExProvider.cs) but if the request/response is dramatically different you may need to create a SmartPostProvider.

Kyle

**Comment by StephenPAdams** [comment]
I might have to end up adding this feature to DotNetShipping per a client's requirements. If so, I'll submit a pull request once created.

**Comment by kylewest** [comment]
Awesome. Would appreciate that!

kyle

**Comment by StephenPAdams** [comment]
@cjones-swarm  and @kylewest I have something working on my fork. Essentially I ended up creating a new FedEx SmartPost provider because there were enough nuances between the current FedEx rate lookup and the SmartPost rate lookup request that I thought it'd be better to separate them. If you want to give it a preliminary look, it's located here: https://github.com/StephenPAdams/DotNetShipping

Unfortunately I wasn't following best practices, so my fork is out of date from yours, @kylewest . So I'll do some finagling to get this so I can get a clean pull request your way later this week. Thoughts?

**Comment by StephenPAdams** [comment]
And pull request created :)
https://github.com/kylewest/DotNetShipping/pull/51

Hopefully this works for your use cases!

**Comment by kylewest** [comment]
closed by #51

**Comment by StephenPAdams** [comment]
Awesome! Thanks @kylewest :) Love this library.

**Comment by kylewest** [comment]
no problem @StephenPAdams ... you did all the work. BTW, added you to the credits. when I was doing so noticed you are in Baltimore. shoot me an email sometime, I'm just outside DC in MD.

**Comment by StephenPAdams** [comment]
Very cool! Definitely. Although I don't have your email addy @kylewest ! One of GitHub's quirky nature is not being able to DM.

**Comment by kylewest** [comment]
click @kylewest .. it's in there 👍 

![image](https://cloud.githubusercontent.com/assets/6247/18918002/601a432c-8567-11e6-8ee4-baa6240d2db4.png)
