### ISSUE TITLE
FedEx: Add option for development vs. production environments

### ISSUE THREAD

**Issue by sahartash** [kylewest/DotNetShipping#40]
![image](https://cloud.githubusercontent.com/assets/14878241/13336222/c8ae0830-dbc9-11e5-9fa0-9d80779180b2.png)

**Comment by vincentw56** [comment]
I just tried it with your address information and it worked fine. Currently, it looks like FedEx dev environment is having issues getting any other rate than Ground. Since I don't have your FedEx account information, I cannot tell if it is an issue with your account. If you set a break point in the FedExProvider.cs file at line 136 (I think), you can check any replies coming back. Here is a screenshot:

![capture](https://cloud.githubusercontent.com/assets/1850511/13437697/8b0c8784-dfb3-11e5-8426-015f993b7e6b.JPG)

You can also download the files from FedEx and use it to make sure it is working.

[https://www.fedex.com/us/developer/web-services/process.html?tab=tab2](url)

**Comment by carlosredondo** [comment]
We experienced this same bug, and we found that Fedex integration wasn't returning rate information because Fedex class provider was configured to use production URL as default.

**Comment by kylewest** [comment]
closed by #51
